const products=[
 {id:1,name:'The Sunday Blue Jeans',category:'Jeans',price:890,condition:'Excellent',vendor:'Closet Stories · Jaipur',tag:'Vintage verified',image:'photo-1541099649105-f69ad21f3246',origin:'A sturdy pair of 90s straight-leg denim, found at a Sunday flea in Jaipur. Gently broken in, never broken down.',history:['1996 · Made in a small denim unit in Gujarat','2010 · First loved by Ananya’s older sister','2024 · Found and cared for by Closet Stories','Today · Ready for its next chapter with you'],size:'28',color:'Indigo'},
 {id:2,name:'Gulabi Patchwork Jacket',category:'Jackets',price:1450,condition:'Very good',vendor:'Mending Mood · Mumbai',tag:'One of a kind',image:'photo-1548126032-079a0fb0099d',origin:'A cotton jacket given a second life with hand-cut scraps from other loved garments. Each patch is stitched by hand.',history:['Unknown · The original jacket began its life in a Mumbai wardrobe','2023 · Saved from a textile discard pile','2024 · Patchworked by Meera at Mending Mood','Today · A one-off piece, made to be worn out'],size:'M',color:'Rose & indigo'},
 {id:3,name:'Mogra Cotton Kurti',category:'Kurtis',price:720,condition:'Excellent',vendor:'Neem & Needle · Pune',tag:'Vintage verified',image:'photo-1583391733956-6c78276477e5',origin:'Soft handloom cotton with tiny block-printed mogra blooms. Airy, easy, and freshly repaired at the hem.',history:['2008 · Woven and printed in Bagru, Rajasthan','2009 · Worn and loved by a Pune family','2024 · Repaired and listed by Neem & Needle','Today · Ready for slow mornings and long lunches'],size:'M',color:'Ivory & green'},
 {id:4,name:'Market Day Stripe Shirt',category:'Tops',price:560,condition:'Very good',vendor:'Second Sun · Bengaluru',tag:'Brand verified',image:'photo-1596755094514-f87e34085b2c',origin:'A relaxed cotton shirt with a lived-in feel. Label checked in person and buttons all present.',history:['2019 · Made by a responsible Indian label','2020 · Bought in Bengaluru and worn on repeat','2024 · Checked and cleaned by Second Sun','Today · Your new easy favourite'],size:'S',color:'Blue stripe'},
 {id:5,name:'Aunty’s Garden Dress',category:'Dresses',price:1180,condition:'Excellent',vendor:'Closet Stories · Jaipur',tag:'One of a kind',image:'photo-1496747611176-843222e1e57c',origin:'A cheerful floral midi dress passed down through cousins. The original owner added pockets (the best kind of history).',history:['2017 · Sewn in Jaipur for a family wedding','2018–22 · Shared between three cousins','2024 · Freshly laundered and listed by Closet Stories','Today · Pockets and all, it’s yours'],size:'S',color:'Rust floral'},
 {id:6,name:'Chai Break Crochet Top',category:'Tops',price:680,condition:'Good',vendor:'Dori Dori · Delhi',tag:'Handmade',image:'photo-1576566588028-4147f3842f27',origin:'Hand-crocheted cotton in a warm chai shade. A small repaired loop near the shoulder is part of its charm.',history:['2016 · Crocheted by hand in Delhi','2016–23 · Loved through many summers','2024 · Loop repaired by Dori Dori','Today · A handmade piece looking for a new chai buddy'],size:'M',color:'Chai'},
 {id:7,name:'Old-Soul Corduroy Pants',category:'Trousers',price:990,condition:'Very good',vendor:'The Rewear Room · Kochi',tag:'Vintage verified',image:'photo-1506629905607-d9f3f7424c88',origin:'High-waist corduroy with a soft patina at the knees. Pockets, zip, and seams all checked and ready.',history:['1990s · Cut and sewn in a small Indian workshop','2000s · Worn around Fort Kochi','2024 · Carefully sourced by The Rewear Room','Today · Ready for your next big plan'],size:'30',color:'Tobacco'},
 {id:8,name:'Little Marigold Scarf',category:'Accessories',price:380,condition:'Excellent',vendor:'Neem & Needle · Pune',tag:'Vintage verified',image:'photo-1601924994987-69e26d50dc26',origin:'Light cotton scarf with hand-blocked marigolds. Washes beautifully and styles even better.',history:['2012 · Block-printed in Jaipur','2013–22 · Loved as a scarf, wrap and table runner','2024 · Passed to Neem & Needle for its next life','Today · A little sunshine, wherever you tie it'],size:'One size',color:'Marigold'},
 {id:9,name:'Blue Hour Denim Skirt',category:'Skirts',price:790,condition:'Very good',vendor:'Second Sun · Bengaluru',tag:'Brand verified',image:'photo-1583496661160-fb5886a0aaaa',origin:'A perfectly easy A-line denim skirt. Authenticated label, sturdy stitching, and one tiny repair at the back pocket.',history:['2015 · Made by an Indian denim label','2018 · Worn on Bengaluru city walks','2024 · Pocket stitching restored by Second Sun','Today · Ready for another round of plans'],size:'28',color:'Washed blue'},
 {id:10,name:'Sunday Market Tote',category:'Accessories',price:420,condition:'Good',vendor:'Dori Dori · Delhi',tag:'Upcycled',image:'photo-1590874103328-eac38a683ce7',origin:'Made from sturdy cotton offcuts. Has a little fading and a lot of room for market day finds.',history:['2021 · Cut from leftover canvas in Delhi','2022–23 · Used as a studio sample bag','2024 · Reinforced handles by Dori Dori','Today · Ready for all the things you carry'],size:'One size',color:'Natural'},
 {id:11,name:'Terracotta Knit Vest',category:'Tops',price:850,condition:'Excellent',vendor:'Mending Mood · Mumbai',tag:'Vintage verified',image:'photo-1618354691373-d851c5c3a990',origin:'A warm knit vest with a classic fit. Vintage label inspected and all knitwear gently de-pilled by the vendor.',history:['1990s · Knitted in India','1990s–2022 · A much-loved family layer','2024 · Refreshed by Mending Mood','Today · Looking for a new layering story'],size:'M',color:'Terracotta'},
 {id:12,name:'Rainy Day Denim Shirt',category:'Shirts',price:940,condition:'Very good',vendor:'The Rewear Room · Kochi',tag:'Brand verified',image:'photo-1598033129183-c4f50c736f10',origin:'Soft washed denim with a relaxed fit. Carefully checked, fresh buttons, and no surprises.',history:['2018 · Made in a small-batch Indian workshop','2019–23 · Worn as a shirt, then a light jacket','2024 · Cleaned and verified by The Rewear Room','Today · A versatile next chapter starts here'],size:'L',color:'Deep blue'},
 {id:13,name:'Patch Pocket Work Shirt',category:'Shirts',price:640,condition:'Good',vendor:'Closet Stories · Jaipur',tag:'One of a kind',image:'photo-1603252109303-2751441dd157',origin:'A sturdy work shirt with bright, hand-sewn patches over a tiny old mark. Visible mending made the detail.',history:['2017 · A workshop uniform in Jaipur','2020 · Retired to the back of a cupboard','2024 · Given new colour by Closet Stories','Today · Made for getting out there again'],size:'L',color:'Olive'},
 {id:14,name:'Lilac Daydream Kurti',category:'Kurtis',price:820,condition:'Excellent',vendor:'Neem & Needle · Pune',tag:'Handmade',image:'photo-1585487000160-6ebcfceb0d03',origin:'A soft cotton kurti with gentle gathers and handmade shell buttons. Easy to dress up or down.',history:['2020 · Tailored in Pune by a neighbourhood darzi','2021–23 · Worn for family get-togethers','2024 · Buttons refreshed by Neem & Needle','Today · Ready for your everyday rituals'],size:'S',color:'Lilac'}
];
const cats=['Everything','Jeans','Tops','Kurtis','Dresses','Shirts','Trousers','Jackets','Skirts','Accessories'];let activeCategory='Everything',cart=JSON.parse(localStorage.getItem('rewear-cart')||'[]'),saved=JSON.parse(localStorage.getItem('rewear-saved')||'[]'),points=Number(localStorage.getItem('rewear-points')||'0'),visible=8,conditions=[],tags=[],priceLimit=9999;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const indiaImages={
 'photo-1541099649105-f69ad21f3246':'https://images.pexels.com/photos/37800869/pexels-photo-37800869/free-photo-of-fashionable-woman-walking-in-mumbai-street.jpeg?auto=compress&cs=tinysrgb&w=1000',
 'photo-1548126032-079a0fb0099d':'https://avartanavenue.com/cdn/shop/files/upcycled-denim-jacket-indian-fabric-applique_front.jpg?v=1750415982&width=1200',
 'photo-1583391733956-6c78276477e5':'https://images.pexels.com/photos/35445207/pexels-photo-35445207/free-photo-of-south-asian-woman-in-pink-kurta-on-mumbai-street.jpeg?auto=compress&cs=tinysrgb&w=1000',
 'photo-1596755094514-f87e34085b2c':'https://images.pexels.com/photos/35489831/pexels-photo-35489831/free-photo-of-trendy-woman-walking-in-urban-mumbai-street.jpeg?auto=compress&cs=tinysrgb&w=1000',
 'photo-1496747611176-843222e1e57c':'https://images.pexels.com/photos/27139262/pexels-photo-27139262/free-photo-of-a-woman-in-a-sari-standing-on-the-street.jpeg?auto=compress&cs=tinysrgb&w=1000',
 'photo-1576566588028-4147f3842f27':'https://images.pexels.com/photos/29601839/pexels-photo-29601839/free-photo-of-cheerful-woman-in-traditional-indian-attire.jpeg?auto=compress&cs=tinysrgb&w=1000',
 'photo-1506629905607-d9f3f7424c88':'https://images.pexels.com/photos/35489831/pexels-photo-35489831/free-photo-of-trendy-woman-walking-in-urban-mumbai-street.jpeg?auto=compress&cs=tinysrgb&w=1000',
 'photo-1601924994987-69e26d50dc26':'https://images.unsplash.com/photo-1773846012458-e6a66c26e49f?auto=format&fit=crop&w=1000&q=82',
 'photo-1583496661160-fb5886a0aaaa':'https://images.pexels.com/photos/37800869/pexels-photo-37800869/free-photo-of-fashionable-woman-walking-in-mumbai-street.jpeg?auto=compress&cs=tinysrgb&w=1000',
 'photo-1590874103328-eac38a683ce7':'https://images.pexels.com/photos/34315492/pexels-photo-34315492/free-photo-of-colorful-indian-bazaar-with-woman-in-traditional-attire.jpeg?auto=compress&cs=tinysrgb&w=1000',
 'photo-1618354691373-d851c5c3a990':'https://images.pexels.com/photos/35489831/pexels-photo-35489831/free-photo-of-trendy-woman-walking-in-urban-mumbai-street.jpeg?auto=compress&cs=tinysrgb&w=1000',
 'photo-1598033129183-c4f50c736f10':'https://images.pexels.com/photos/37800869/pexels-photo-37800869/free-photo-of-fashionable-woman-walking-in-mumbai-street.jpeg?auto=compress&cs=tinysrgb&w=1000',
 'photo-1603252109303-2751441dd157':'https://avartanavenue.com/cdn/shop/files/upcycled-denim-jacket-indian-fabric-applique_front.jpg?v=1750415982&width=1200',
 'photo-1585487000160-6ebcfceb0d03':'https://images.pexels.com/photos/35445207/pexels-photo-35445207/free-photo-of-south-asian-woman-in-pink-kurta-on-mumbai-street.jpeg?auto=compress&cs=tinysrgb&w=1000'
};
function photo(id,w=700){return indiaImages[id]||`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=82`}
localStorage.setItem('rewear-products',JSON.stringify(products.map(p=>({...p,imageUrl:photo(p.image,500)}))));
const sewnHeart='<svg class="stitch-icon heart-stitch" viewBox="0 0 24 24" aria-hidden="true"><path d="M20.4 8.7c0 5-8.4 10.3-8.4 10.3S3.6 13.7 3.6 8.7A4.3 4.3 0 0 1 12 6.4a4.3 4.3 0 0 1 8.4 2.3Z"/></svg>';
function initCats(){$('#categories').innerHTML=cats.map(c=>`<button class="category-chip ${c===activeCategory?'active':''}" data-category="${c}">${c}</button>`).join('');$$('.category-chip').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.category;visible=8;initCats();renderProducts()})}
function getFiltered(){let q=$('#search-input').value.trim().toLowerCase(),sort=$('#sort-select').value;let p=products.filter(x=>(activeCategory==='Everything'||x.category===activeCategory)&&(!q||`${x.name} ${x.category} ${x.vendor} ${x.tag}`.toLowerCase().includes(q))&&(!conditions.length||conditions.includes(x.condition))&&(!tags.length||tags.includes(x.tag))&&x.price<=priceLimit);if(sort==='low')p.sort((a,b)=>a.price-b.price);if(sort==='high')p.sort((a,b)=>b.price-a.price);if(sort==='recent')p.sort((a,b)=>b.id-a.id);return p}
function renderProducts(){let all=getFiltered(),items=all.slice(0,visible);$('#result-count').textContent=`${all.length} little find${all.length===1?'':'s'}`;$('#active-filters').innerHTML=[...conditions,...tags,...(priceLimit<9999?[`Under ₹${priceLimit}`]:[])].map(x=>`<span class="active-filter">${x}<button data-remove="${x}">×</button></span>`).join('');$('#product-grid').innerHTML=items.length?items.map(p=>`<article class="product-card" data-id="${p.id}"><div class="product-image-wrap"><img loading="lazy" class="product-image" src="${photo(p.image)}" alt="${p.name}"/><span class="product-badge">${p.tag.toUpperCase()}</span><button class="heart-button ${saved.includes(p.id)?'saved':''}" data-save="${p.id}" aria-label="${saved.includes(p.id)?'Remove from':'Add to'} wishlist">${saved.includes(p.id)?'♥':'♡'}</button></div><div class="product-info"><p class="vendor-name">${p.vendor}</p><h3 class="product-name">${p.name}</h3><div class="product-meta"><span class="product-price">₹${p.price.toLocaleString('en-IN')}</span><span class="product-condition">${p.condition} · ${p.size}</span></div><div class="vendor-mark">✳ Seller checked · Earn 100 threads</div></div></article>`).join(''):`<div class="empty-state"><div style="font-size:28px">✳</div><h3>No finds just yet</h3>Try a different search or clear a filter.</div>`;$('#load-more').style.display=all.length>visible?'flex':'none';$$('.product-card').forEach(c=>c.onclick=e=>{if(!e.target.closest('[data-save]'))openProduct(+c.dataset.id)});$$('[data-save]').forEach(b=>b.onclick=e=>{e.stopPropagation();let id=+b.dataset.save;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem('rewear-saved',JSON.stringify(saved));renderProducts();toast(saved.includes(id)?'Saved to your wishlist ♡':'Removed from your wishlist')});$$('[data-remove]').forEach(b=>b.onclick=()=>{let x=b.dataset.remove;conditions=conditions.filter(v=>v!==x);tags=tags.filter(v=>v!==x);if(x.startsWith('Under'))priceLimit=9999;syncFilters();renderProducts()})}
function openProduct(id){const p=products.find(x=>x.id===id);$('#modal-content').innerHTML=`<div class="product-detail"><img class="detail-image" src="${photo(p.image,900)}" alt="${p.name}"/><div class="detail-copy"><span class="detail-vendor">${p.vendor}</span><h2>${p.name}</h2><div class="detail-price">₹${p.price.toLocaleString('en-IN')}</div><div class="detail-condition">${p.condition} condition · Size ${p.size} · ${p.color}</div><div class="verified-row"><span class="verified-tag">✳ ${p.tag}</span><span class="verified-tag">✳ Seller checked</span></div><p>${p.origin}</p><h3>Its little life so far</h3><ul class="history-list">${p.history.map(x=>`<li>${x}</li>`).join('')}</ul><label class="detail-vendor">Size<select class="size-select" id="size-select"><option>${p.size}</option></select></label><button class="button button-dark" id="add-to-cart">Add to bag · ₹${p.price.toLocaleString('en-IN')} <span>↗</span></button><p>Earn 100 Thread points when you bring this find home.</p></div></div>`;openModal();$('#add-to-cart').onclick=()=>{addCart(id);closeModal();openDrawer('cart-drawer')}}
function addCart(id){const item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,qty:1});saveCart();toast('A good find, added to your bag ✳')}
function saveCart(){localStorage.setItem('rewear-cart',JSON.stringify(cart));updateCart()}
function updateCart(){let count=cart.reduce((n,x)=>n+x.qty,0);$$('.cart-count').forEach(x=>x.textContent=count);$$('.cart-count-text').forEach(x=>x.textContent=`(${count})`);let body=$('#cart-items'),foot=$('#cart-foot');if(!cart.length){body.innerHTML='<div class="empty-cart"><div style="font-size:35px">♧</div>Your bag is looking for a good story.<br><a class="text-link" href="#shop" data-close>Find a little something ↗</a></div>';foot.innerHTML='<p class="points-note">Every find earns you 100 Thread points.</p>';return}body.innerHTML=cart.map(({id,qty})=>{let p=products.find(a=>a.id===id);return `<div class="cart-row"><img src="${photo(p.image,200)}" alt=""><div><p>${p.vendor}</p><h3>${p.name}</h3><b>₹${p.price.toLocaleString('en-IN')}</b><div class="quantity-controls"><button data-qty="${id}" data-change="-1">−</button>${qty}<button data-qty="${id}" data-change="1">+</button></div><button class="remove-item" data-remove-cart="${id}">Remove</button></div><b>₹${(p.price*qty).toLocaleString('en-IN')}</b></div>`}).join('');let total=cart.reduce((n,x)=>n+products.find(p=>p.id===x.id).price*x.qty,0);foot.innerHTML=`<p class="cart-summary"><span>Subtotal</span><b>₹${total.toLocaleString('en-IN')}</b></p><p class="points-note">This order earns ${count*100} Thread points ✳</p><button class="button button-dark" id="checkout-button">Continue to checkout <span>↗</span></button><button class="button button-outline" data-close>Keep browsing</button>`;$$('[data-qty]').forEach(b=>b.onclick=()=>{let id=+b.dataset.qty,item=cart.find(x=>x.id===id);item.qty+=+b.dataset.change;if(item.qty<1)cart=cart.filter(x=>x.id!==id);saveCart()});$$('[data-remove-cart]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==+b.dataset.removeCart);saveCart()});$('#checkout-button').onclick=checkout}
function checkout(){closeDrawer();if(location.hash!=='#checkout')location.hash='checkout';window.mountBilliCheckout()}
function openDrawer(id){$('#overlay').classList.add('open');$('#'+id).classList.add('open');document.body.style.overflow='hidden'}function closeDrawer(){$('.drawer.open')?.classList.remove('open');$('#overlay').classList.remove('open');document.body.style.overflow=''}function openModal(){$('#modal-wrap').classList.add('open');document.body.style.overflow='hidden'}function closeModal(){$('#modal-wrap').classList.remove('open');document.body.style.overflow=''}
function toast(s){let t=$('#toast');t.textContent=s;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2400)}
function syncFilters(){$$('input[name=condition]').forEach(x=>x.checked=conditions.includes(x.value));$$('input[name=tag]').forEach(x=>x.checked=tags.includes(x.value));$('#price-filter').value=priceLimit}
function serviceModal(type){let donate=type==='donate';$('#modal-content').innerHTML=`<div class="service-modal"><p class="eyebrow">${donate?'PASS THE GOOD ON':'MAKE IT YOURS AGAIN'}</p><h2>${donate?'A fresh start for your clothes.':'Let’s dream up a remake.'}</h2><p>${donate?'Tell us a little about your donation and we’ll help arrange a local drop-off or pick-up.':'Tell us what you have in mind. Our mending partners can add patchwork, visible mending, or a whole new point of view.'}</p><form class="service-form" id="service-form"><label>Your name<input required name="name" placeholder="What should we call you?"></label><label>Email address<input required type="email" name="email" placeholder="you@example.com"></label><label>${donate?'What are you passing on?':'What would you like to change?'}<textarea required name="details" placeholder="A few details help us get started…"></textarea></label>${donate?'':'<label>Choose your vibe<select name="style"><option>Patchwork</option><option>Visible mending</option><option>Embroidery</option><option>Let’s decide together</option></select></label>'}<button class="button button-dark">${donate?'Plan my donation':'Start my upcycle'} <span>↗</span></button></form></div>`;openModal();$('#service-form').onsubmit=e=>{e.preventDefault();closeModal();toast(donate?'Lovely. We’ll be in touch about your donation ✳':'Lovely. Your remake idea is on its way ✳')}}
function rewards(){let toGo=Math.max(0,500-points),pct=Math.min(100,points/5);$('#modal-content').innerHTML=`<div class="reward-modal"><p class="eyebrow">THE GOOD KARMA CLUB</p><h2 style="font-family:var(--serif);font-size:31px;font-weight:500">Your Thread points</h2><div class="reward-big">${points}</div><div class="reward-note">THREADS IN YOUR POCKET</div><div class="reward-track"><span style="width:${pct}%"></span></div><p class="reward-note">${toGo?`You’re ${toGo} points away from a freebie. Earn 100 with each item.`:'You have 500 points! Pick a little freebie at checkout.'}</p><button class="button button-dark" id="reward-shop">Find a good thing <span>↗</span></button></div>`;openModal();$('#reward-shop').onclick=()=>{closeModal();document.querySelector('#shop').scrollIntoView({behavior:'smooth'})}}
function showSearch(){document.querySelector('#shop').scrollIntoView({behavior:'smooth'});setTimeout(()=>$('#search-input').focus(),350)}
const renderProductsBase=renderProducts;
renderProducts=function(){renderProductsBase();$$('[data-save]').forEach(button=>button.innerHTML=sewnHeart)};
$$('.category-card').forEach(button=>button.addEventListener('click',()=>{activeCategory=button.dataset.category;visible=8;initCats();renderProducts();document.querySelector('#shop').scrollIntoView({behavior:'smooth'})}));
initCats();renderProducts();updateCart();$('#search-input').addEventListener('input',()=>{visible=8;renderProducts()});$('#sort-select').addEventListener('change',renderProducts);$('#load-more').onclick=()=>{visible+=4;renderProducts()};$('.bag-button').onclick=()=>openDrawer('cart-drawer');$('#filter-button').onclick=()=>openDrawer('filter-drawer');$('.search-toggle').onclick=showSearch;$('.account-button').onclick=rewards;$('#rewards-link').onclick=rewards;$('#overlay').onclick=closeDrawer;document.addEventListener('click',e=>{if(e.target.closest('[data-close]')){closeDrawer();closeModal()}});$$('.service-action').forEach(b=>b.onclick=()=>serviceModal(b.dataset.service));$('#apply-filters').onclick=()=>{conditions=$$('input[name=condition]:checked').map(x=>x.value);tags=$$('input[name=tag]:checked').map(x=>x.value);priceLimit=+$('#price-filter').value;closeDrawer();renderProducts()};$('#clear-filters').onclick=()=>{conditions=[];tags=[];priceLimit=9999;syncFilters();renderProducts()};$('#modal-wrap').onclick=e=>{if(e.target===$('#modal-wrap'))closeModal()};$('.menu-toggle').onclick=()=>$('.main-nav').classList.toggle('open');$$('.main-nav a').forEach(link=>link.addEventListener('click',()=>$('.main-nav').classList.remove('open')));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDrawer();closeModal();$('.main-nav').classList.remove('open')}});$('#newsletter-form').onsubmit=e=>{e.preventDefault();toast('You’re on the list. Good finds are coming ✳');e.target.reset()};
if(location.hash==='#checkout')window.mountBilliCheckout();
window.addEventListener('hashchange',()=>{if(location.hash==='#checkout')window.mountBilliCheckout();else window.closeBilliCheckout()});
if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
