(function(){
  const money=value=>'₹'+Math.round(value).toLocaleString('en-IN');
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'')}catch{return fallback}};
  const imageFor=p=>p.imageUrl||('https://images.unsplash.com/'+p.image+'?auto=format&fit=crop&w=500&q=82');
  function closeCheckout(){const route=document.querySelector('#checkout-route');if(route)route.remove()}
  function mountCheckout(){
    if(!window.BilliAccount?.current()){location.hash='top';window.BilliAccount?.open({resumeCheckout:true});return}
    if(document.querySelector('#checkout-route'))return;
    const route=document.createElement('div');route.id='checkout-route';route.className='checkout-route checkout-page';
    route.innerHTML='<div class="announcement">BILLI BAZAAR · INDIAN THRIFT · FREE DELIVERY ON ORDERS OVER ₹999</div>'+
      '<header class="site-header checkout-header"><a class="wordmark" href="#top" aria-label="Billi Bazaar home">billi <span>bazaar</span><img class="brand-cat" src="./billi-cat-logo.png" alt="" aria-hidden="true"></a><button class="checkout-back" id="checkout-back">← Continue shopping</button><span class="checkout-secure">Secure checkout</span></header>'+
      '<main class="checkout-main" id="checkout-main"><div class="checkout-intro"><p class="eyebrow">ORDER DETAILS</p><h1>Checkout</h1><p>Review your items, delivery details and payment.</p></div>'+
      '<div class="checkout-layout"><form class="checkout-form" id="checkout-form">'+
      '<section class="checkout-section"><div class="checkout-section-heading"><span>01</span><div><p class="eyebrow">CONTACT</p><h2>Contact details</h2></div></div><div class="checkout-fields two-col">'+
      '<label>Full name<input name="name" autocomplete="name" placeholder="Full name" required></label><label>Mobile number<input name="phone" type="tel" inputmode="numeric" autocomplete="tel-national" placeholder="10-digit number" pattern="[6-9][0-9]{9}" maxlength="10" required><small>We will share delivery updates here.</small></label><label class="field-wide">Email address<input name="email" type="email" autocomplete="email" placeholder="you@example.com" required></label></div></section>'+
      '<section class="checkout-section"><div class="checkout-section-heading"><span>02</span><div><p class="eyebrow">DELIVERY ADDRESS</p><h2>Delivery address</h2></div></div><div class="checkout-fields two-col">'+
      '<label class="field-wide">Street address<input name="address" autocomplete="street-address" placeholder="Flat, house number, street" required></label><label class="field-wide">Landmark <span class="optional">(optional)</span><input name="landmark" placeholder="Nearby landmark"></label><label>City<input name="city" autocomplete="address-level2" placeholder="Your city" required></label><label>PIN code<input name="pincode" inputmode="numeric" autocomplete="postal-code" placeholder="6 digits" pattern="[0-9]{6}" maxlength="6" required></label><label class="field-wide">State<select name="state" autocomplete="address-level1" required><option value="">Choose your state</option><option>Andhra Pradesh</option><option>Assam</option><option>Bihar</option><option>Chandigarh</option><option>Chhattisgarh</option><option>Delhi</option><option>Goa</option><option>Gujarat</option><option>Haryana</option><option>Himachal Pradesh</option><option>Jharkhand</option><option>Karnataka</option><option>Kerala</option><option>Madhya Pradesh</option><option>Maharashtra</option><option>Odisha</option><option>Punjab</option><option>Rajasthan</option><option>Tamil Nadu</option><option>Telangana</option><option>Uttar Pradesh</option><option>Uttarakhand</option><option>West Bengal</option><option>Other</option></select></label></div><label class="save-address"><input type="checkbox" name="saveAddress"> Save these details on this device</label></section>'+
      '<section class="checkout-section payment-section"><div class="checkout-section-heading"><span>03</span><div><p class="eyebrow">PAYMENT</p><h2>Payment method</h2></div></div><div class="payment-options">'+
      '<label class="payment-option"><input type="radio" name="payment" value="UPI" checked><span class="payment-symbol">↗</span><span><b>UPI</b><small>GPay, PhonePe, Paytm &amp; more</small></span><span class="payment-radio"></span></label><label class="payment-option"><input type="radio" name="payment" value="Card"><span class="payment-symbol">▤</span><span><b>Credit or debit card</b><small>Visa, Mastercard, RuPay</small></span><span class="payment-radio"></span></label><label class="payment-option"><input type="radio" name="payment" value="Cash on delivery"><span class="payment-symbol">₹</span><span><b>Cash on delivery</b><small>Pay when your parcel arrives</small></span><span class="payment-radio"></span></label></div><p class="demo-payment-note">This preview records a demo order only. It does not charge a payment method.</p></section>'+
      '<button class="button button-dark place-order" type="submit">Place order <span>↗</span></button><p class="order-assurance">Each item is checked by its seller before dispatch.</p></form>'+
      '<aside class="order-summary" aria-label="Order summary"><div class="summary-head"><div><p class="eyebrow">ORDER SUMMARY</p><h2>Order summary <span id="summary-count"></span></h2></div><button id="edit-bag">Edit bag</button></div><div class="summary-items" id="summary-items"></div><div class="summary-calculation" id="summary-calculation"></div><div class="summary-rewards"><span></span><p><b id="reward-earned">0 Thread points</b><br>Points are added to your account after order confirmation.</p></div><div class="summary-total"><span>Total</span><b id="order-total">₹0</b></div><p class="summary-footnote">Taxes included.</p></aside></div></main>'+
      '<footer class="checkout-footer"><a class="wordmark" href="#top">billi <span>bazaar</span><img class="brand-cat" src="./billi-cat-logo.png" alt="" aria-hidden="true"></a><p>Secondhand style from independent sellers.</p><small>© 2026 Billi Bazaar · Independent Indian thrift marketplace</small></footer>';
    document.body.appendChild(route);
    route.querySelector('#checkout-back').onclick=()=>{location.hash='top'};
    route.querySelector('#edit-bag').onclick=()=>{closeCheckout();openDrawer('cart-drawer')};
    const catalog=read('rewear-products',[]),items=read('rewear-cart',[]).map(row=>({product:catalog.find(p=>p.id===row.id),qty:Math.max(1,Number(row.qty)||1)})).filter(row=>row.product);
    const count=items.reduce((sum,row)=>sum+row.qty,0),subtotal=items.reduce((sum,row)=>sum+row.product.price*row.qty,0),delivery=subtotal===0||subtotal>=999?0:80,main=route.querySelector('#checkout-main');
    if(!items.length){main.innerHTML='<div class="checkout-empty"><div class="success-mark">♧</div><p class="eyebrow">YOUR BAG IS EMPTY</p><h1>Your bag is empty.</h1><p>Add an item to your bag before checkout.</p><button class="button button-dark" id="empty-bag-back">Browse products ↗</button></div>';route.querySelector('#empty-bag-back').onclick=()=>{location.hash='shop'};return}
    route.querySelector('#summary-count').textContent='('+count+')';
    route.querySelector('#summary-items').innerHTML=items.map(row=>'<article class="summary-item"><img src="'+imageFor(row.product)+'" alt="'+row.product.name+'"><div><p class="summary-item-vendor">'+row.product.vendor+'</p><h3>'+row.product.name+'</h3><small>Size '+row.product.size+' · Qty '+row.qty+'</small></div><b class="summary-item-price">'+money(row.product.price*row.qty)+'</b></article>').join('');
    route.querySelector('#summary-calculation').innerHTML='<p class="summary-line"><span>Subtotal</span><span>'+money(subtotal)+'</span></p><p class="summary-line"><span>Delivery</span><span class="free-delivery">'+(delivery?money(delivery):'FREE')+'</span></p>';
    const account=window.BilliAccount.current();route.querySelector('#reward-earned').textContent='+'+(count*100)+' Thread points · Balance '+(account.points||0);if(account.freebieReserved)route.querySelector('.summary-rewards p').insertAdjacentHTML('beforeend','<br><b>Your redeemed freebie is reserved for this order.</b>');route.querySelector('#order-total').textContent=money(subtotal+delivery);
    const saved=read('rewear-address',null),form=route.querySelector('#checkout-form');if(saved){for(const key of ['name','phone','email','address','landmark','city','pincode','state'])if(saved[key])form.elements[key].value=saved[key];form.elements.saveAddress.checked=true}const profile=window.BilliAccount.current();if(profile){if(!form.elements.name.value)form.elements.name.value=profile.name;if(!form.elements.phone.value)form.elements.phone.value=profile.phone}
    form.onsubmit=event=>{event.preventDefault();if(!form.reportValidity())return;const data=new FormData(form);if(data.has('saveAddress'))localStorage.setItem('rewear-address',JSON.stringify(Object.fromEntries(['name','phone','email','address','landmark','city','pincode','state'].map(key=>[key,String(data.get(key)||'').trim()]))));const order={reference:'BB-'+Math.floor(100000+Math.random()*900000),name:String(data.get('name')).trim(),payment:data.get('payment'),points:count*100,total:subtotal+delivery};const hadFreebie=Boolean(window.BilliAccount.current()?.freebieReserved);window.BilliAccount.completeOrder(order.points,order.reference);order.freebieIncluded=hadFreebie; localStorage.setItem('rewear-last-order',JSON.stringify(order));localStorage.setItem('rewear-cart','[]');main.innerHTML='<section class="order-success"><div class="success-mark"></div><p class="eyebrow">ORDER CONFIRMED · '+order.payment.toUpperCase()+'</p><h1>Order confirmed</h1><p>Thank you, '+order.name+'. Your order has been received.</p><div class="success-meta">Order reference<br><b>'+order.reference+'</b><br><br><strong>+'+order.points+' Thread points</strong> earned'+(order.freebieIncluded?'<br><br><strong>A redeemed freebie is included</strong>':'')+'</div><button class="button button-dark" id="finish-order">Back to Billi Bazaar ↗</button></section>';route.querySelector('#finish-order').onclick=()=>{location.hash='top'};window.scrollTo({top:0,behavior:'smooth'})};
  }
  window.mountBilliCheckout=mountCheckout;window.closeBilliCheckout=closeCheckout;
})();
